### ISSUE TITLE
Asset List Search & Filter

### ISSUE THREAD

**Issue by fashxp** [pimcore/studio-ui-bundle#176]
![image](https://github.com/pimcore/product-management/assets/8792145/598422ea-55a1-4805-8a69-54b28badd574)

**Comment by ValeriaMaltseva** [comment]
The front-end part consists of four parts and will be implemented in four separate PRs.

1. ✅ Full-text search filter (the back-end part will be implemented in this task: https://github.com/pimcore/studio-backend-bundle/issues/523).
2. ✅ "only direct children" checkbox filter (the "only unreferenced" is currently on hold).
3. ✅ PQL filter.
4. Field filters: 
     1. ✅ Fix ID field.
     2. ✅ Add Datetime field.
     3. ✅ Add Fullpath field.
