### ISSUE TITLE
Asset List Selection Actions (CSV Export, ZIP Download)

### ISSUE THREAD

**Issue by fashxp** [pimcore/studio-ui-bundle#178]
![image](https://github.com/pimcore/product-management/assets/8792145/942cc165-79c2-4ce1-93d0-933f047514c6)

**Comment by markus-moser** [comment]
Related to. https://github.com/pimcore/studio-backend-bundle/issues/137

**Comment by lukmzig** [comment]
ZIP archive to download can be created under this route:
https://github.com/pimcore/studio-backend-bundle/blob/1.x/src/Asset/Controller/CreateZipController.php#L49
This will trigger GEE job, when its finished, the zip can be download here based on the jobrun ID
https://github.com/pimcore/studio-backend-bundle/blob/1.x/src/Asset/Controller/DownloadZipController.php#L49

CSV export can be created under this route:
https://github.com/pimcore/studio-backend-bundle/blob/1.x/src/Asset/Controller/CreateCsvController.php#L48
This will trigger GEE job, when its finished, the csv file can be download here based on the jobrun ID
https://github.com/pimcore/studio-backend-bundle/blob/1.x/src/Asset/Controller/DownloadCsvController.php#L54
