### ISSUE TITLE
Login - Login Screen

### ISSUE THREAD

**Issue by fashxp** [pimcore/studio-ui-bundle#255]
![image](https://github.com/pimcore/studio-ui-bundle/assets/8792145/a9a73c00-0cee-40ff-ab93-067f0c5332f1)

https://www.figma.com/design/kTxowT29eCHwNh5NspDGGu/Pimcore-Components?node-id=3010-105285&t=TH6LzmPptxSxTMON-4

**Comment by markus-moser** [comment]
Related to #110

**Comment by Corepex** [comment]
this task is already done - time to celebrate :tada:
