### ISSUE TITLE
Asset Upload

### ISSUE THREAD

**Issue by fashxp** [pimcore/studio-ui-bundle#257]
- Single Upload
- Multi Upload
- ZIP Upload
- Upload via d&d 
- use browser defaults as far as possible

**Comment by markus-moser** [comment]
**@pimcore-studio-backend-team**

I put this to your backlog but have the feeling that we should split the topic up into separate issues. If you would like to discuss details with the UI team please just let me know so that we can arrange a discussion.

**Comment by lukmzig** [comment]
Approach from the API:
- separate endpoint for single upload (this will be also used for the multi-upload)
- separate endpoint for asset replacement
- multi upload will use 1 endpoint to get info if assets with same path are already existing. If yes, FE can give the option to users to either upload copy (single upload endpoint) or replace the content (separate endpoint for asset replace)
- separate endpoint for ZIP upload (should be using GEE for better performance)
- d&d can be handled by single upload endpoint
