### ISSUE TITLE
Data Object Tree - Basics

### ISSUE THREAD

**Issue by fashxp** [pimcore/studio-ui-bundle#258]
Basic tree with all basic features
- [ ] show data
- [ ] paging
- [ ] inline search

![image](https://github.com/pimcore/studio-ui-bundle/assets/8792145/4d5ba5e5-5270-4a0c-94e5-314c30355347)

https://www.figma.com/design/kTxowT29eCHwNh5NspDGGu/Pimcore-Components?node-id=857-44623&t=TH6LzmPptxSxTMON-4

**Comment by lukmzig** [comment]
@idaiv, @vin0401  here we would also need an icon for data object variants which we could display in the tree

**Comment by idaiv** [comment]
FYI there is an icon proposal, not confirmed yet: (https://www.figma.com/design/kTxowT29eCHwNh5NspDGGu/Pimcore-Components?node-id=5259-210605&t=8RQslZ8QMzaLZadb-4)

For reference, the old icon: 
<img width="31" alt="image" src="https://github.com/user-attachments/assets/2fa93a67-f59d-4203-b61c-0466df203e54">

**Comment by idaiv** [comment]
Hi all! The confirmed icon is here: https://www.figma.com/design/kTxowT29eCHwNh5NspDGGu/Pimcore-Components?node-id=5259-210605&t=XuuBIvPJ6ynSxhl2-4
