### ISSUE TITLE
[Properties] Styling of checkbox column

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-ui-bundle#332]
Should the checkbox value column really be centered? For me this looks a bit strange in combination with other types:
![image](https://github.com/pimcore/studio-ui-bundle/assets/4639428/bed0fe78-4d0f-482c-b59a-57b323e7e8e0)

(follow-up to #324)

**Comment by markus-moser** [comment]
@idaiv This is (currently) the last topic regarding the properties view where maybe some input from design perspective could be helpful. Priority is low here, so it's fine for the moment but if you have an idea how to improve please let us know :)

**Comment by idaiv** [comment]
Hi Markus @markus-moser!
Im wondering whether we can align it to the left only for **wide columns** - such as this case, where obviously there is also other data like path, text, etc. 

And with that thought - keep it center aligned for columns where only checkmarks are available in each row. That way we would have more visual balance in the different column scenarios, even if its not the exact same alignment. 

What do you think?

**Comment by markus-moser** [comment]
Let's just align it left for the properties - it's rarely ever the case that we only have one single checkbox property without other properties. In other cases outside of the properties it makes sense to center them. So let's decide it from case to case. But for the properties left align is better then centering it.

**Comment by idaiv** [comment]
yes, true! As long as the drop target icon is right aligned (so all drop target icons go one under each other in a good sequence), then the content is left aligned and all is well.
