### ISSUE TITLE
[Workflows] Workflow place label styling logic

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-ui-bundle#345]
The workflow place configuration tree offers 2 styling/color related configuration option regarding workflow place labels:

- color
- colorInverted
https://github.com/pimcore/pimcore/blob/11.x/bundles/CoreBundle/src/DependencyInjection/Configuration.php#L1457

**@studio-backend-team**: Please adjust the workflow detail API that it directly outputs those 2 options instead of the current options `backgroundColor`, `fontColor` and `borderColor`. Those values are calculated out of the original 2 configuration options by the workflow engine for the classic bundle UI. As we have a little bit different styling approach in the studio UI those values do not help anymore and we need the original config values to build or new login based on them in the UI.

@Corepex As soon as the backend team updated the API we should implement the logic for the place labels like discribed by @idaiv in this comment https://github.com/pimcore/studio-ui-bundle/pull/338#issuecomment-2165173791 based on the `color` and `colorInverted` options.  

![image](https://github.com/pimcore/studio-ui-bundle/assets/4639428/72c11903-0e0c-4958-8f23-4a1ee4dc6023)

**Comment by lukmzig** [comment]
@markus-moser backend part was adapted in this PR:
https://github.com/pimcore/studio-backend-bundle/pull/140
