### ISSUE TITLE
Asset view breadcrumb and toolbar

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-ui-bundle#346]
Implement like in design in figma (next to each other):

![image](https://github.com/pimcore/studio-ui-bundle/assets/4639428/c88299a9-8efa-43a8-b69b-53788d59d928)

**Comment by markus-moser** [comment]
**@studio-backend-team** For the breadcrumb we would need some kind of additional/adopted endpoint.

![image](https://github.com/pimcore/studio-ui-bundle/assets/4639428/bfd602ba-8081-4fc5-83a2-220eca95f180)

We can get the names of the breadcrumb items out of the asset full path (spltted by '/'), but when someone then clicks on a breadcrumb item the according asset should open and for this we would need the ID of the item.

The easiest way to solve it could be to provide a endpoint like "get asset ID by fullPath". We will need the same at the end also for data objects and documents (if you would like to prepare it already for the other types).

But we are open to discuss a different approach if you prefer an alternative solution.

**Comment by lukmzig** [comment]
Endpoint is available under this route: 
https://github.com/pimcore/studio-backend-bundle/blob/1.x/src/Element/Controller/GetIdByPathController.php#L52

**Comment by Corepex** [comment]
Additional Tasks:
- Remove locate and Info icon from footer bar
