### ISSUE TITLE
[Versions] Asset metadata missing

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-ui-bundle#352]
The version preview should show asset metadata attributes:

![image](https://github.com/pimcore/studio-ui-bundle/assets/4639428/82b33325-26e4-45a6-a6b5-3f4930fcf7a8)

Currently they are missing:
![image](https://github.com/pimcore/studio-ui-bundle/assets/4639428/503e5ed8-745a-453b-9dd4-ef4c0dc54066)

Related to #349

**Comment by markus-moser** [comment]
**@pimcore-studio-backend-team**

Please add the asset metadata attributes to the version endpoint so that we can display them in the preview table.

**Comment by mattamon** [comment]
@markus-moser should we also remove the scheduled tasks since they are actually not versioned?

**Comment by markus-moser** [comment]
@mattamon We need the scheduled attribute for this view:

![image](https://github.com/pimcore/studio-ui-bundle/assets/4639428/64404e00-27d5-4aee-b30f-cc98fcd1a0ca)

It might be possible to achieve the same thing when we additionally ask the scheduled tasks API. But this would be a little bit more complex and as we already have it in place I would vote for keeping it.

**Comment by mattamon** [comment]
@markus-moser Okay got it! 

https://github.com/pimcore/studio-backend-bundle/pull/160 I added the missing metadata here. Can you check if this is already enough?

**Comment by markus-moser** [comment]
@mattamon From what I see in the PR it looks good.

@robertSt7 Could you please check if this is fine?

**Comment by mattamon** [comment]
@markus-moser I left out the additional attributes, because they make no sense, since they are not versioned. If you still want to have them, please let me know :)

**Comment by markus-moser** [comment]
@mattamon I think we can leave them out.

**Comment by mattamon** [comment]
@robertSt7 I am going to merge it so it will be part of 1.x

**Comment by robertSt7** [comment]
see https://github.com/pimcore/studio-ui-bundle/pull/430#pullrequestreview-2194110965
