### ISSUE TITLE
[Versions] Empty versions list

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-ui-bundle#357]
The empty versions list is currently displayed like this:

![image](https://github.com/pimcore/studio-ui-bundle/assets/4639428/9c06ca88-1de9-4183-b1ba-617afcd02a98)

We should hide the buttons and display somehow a nicely formatted message "No versions available" or similar.

Related to #349

**Comment by Corepex** [comment]
@markus-moser @idaiv did you speak about the "placeholders" if there is no result?

**Comment by markus-moser** [comment]
@Corepex Yes, we discussed it again yesterday - Ida is working on that topic 👍

**Comment by idaiv** [comment]
The ticket on my board is here: https://github.com/pimcore/product-management/issues/558#issue-2369441452 will update you when its confirmed :)
