### ISSUE TITLE
[Versions] Version number vs. version ID

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-ui-bundle#360]
In the design we do have consecutive numbers in the card headers instead of the ID:

![image](https://github.com/pimcore/studio-ui-bundle/assets/4639428/16b1a052-db14-405b-85de-d107aa2605a6)

In the implemention we show the ID on both locations:

![image](https://github.com/pimcore/studio-ui-bundle/assets/4639428/d1112082-5f24-436f-9726-e9f1375cb33b)

In addition to that it's in my opinion also important to see the version time (with seconds) in the left panel (see #354). At the end we can get space problems.

Wouldn't it be better if we only show the version date and time instead of the number?

**Comment by markus-moser** [comment]
@idaiv @fashxp I think the design is not optimal here. What's your opinion on that?

**Comment by fashxp** [comment]
@markus-moser  couldn't we use the `versionCount` for that? 
just relying on the date is also not ideal, because it could happen that two versions are generated within one second. that's why we thought of the `versionCount` as that number...

**Comment by markus-moser** [comment]
@fashxp Yes the `versionCount` could be possible but then we maybe have some gaps? But I would still appreciate a lot to see the time on the left side otherwise it could be very hard to navigate to the right version.

**Comment by fashxp** [comment]
Sure thing, time we still need (with seconds). 

Gaps can happen yes, but I wouldn't consider that as a problem.

**Comment by markus-moser** [comment]
@idaiv I'm afraid when we display the time with seconds that we will get space problems. Do you have an idea how to display the version count number, the date and the time (with seconds)?

**Comment by markus-moser** [comment]
> @idaiv I'm afraid when we display the time with seconds that we will get space problems. Do you have an idea how to display the version count number, the date and the time (with seconds)?

Ahh, please forget it - it should work ;)

**Comment by markus-moser** [comment]
@fashxp Thanks for clarifying. I created a new issue for the implementation (#363).

-> closed
