### ISSUE TITLE
[Versions] Preview image thumbnails

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-ui-bundle#361]
The version preview images need to be thumbnails:

![image](https://github.com/pimcore/studio-ui-bundle/assets/4639428/c49e875f-30de-48f2-afdd-758bd69138c0)

Currently it seems that the full image content get's displayed. This works for the small assets in the demo but will fail for big assets (or even strange formats like *.psd).

Related to #349

**Comment by markus-moser** [comment]
**@pimcore-studio-backend-team**

Could you please check if we deliver thumbnails for the version preview API?

**Comment by mattamon** [comment]
@markus-moser 
Do we need the original file or do we just need the thumbnail?

**Comment by markus-moser** [comment]
@mattamon We just need the thumbnail
