### ISSUE TITLE
[Schedule] Display translation key instead of techical value in action column

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-ui-bundle#367]
* The dropdown shows nicely translated values whereas the column content is displayed without translation keys:

![image](https://github.com/pimcore/studio-ui-bundle/assets/4639428/03d5b35c-9bd8-4443-97d3-6088250f2008)

* The column value should not be centered but left aligned like in the design:

![image](https://github.com/pimcore/studio-ui-bundle/assets/4639428/79f047b7-ec47-4148-91c7-4db7612de5b4)

* Also the select styling (with purple color and arrow for the dropdown) for the action picker is not like in the design.

Related to #348

**Comment by Corepex** [comment]
![image](https://github.com/pimcore/studio-ui-bundle/assets/16717695/bb6ddcf9-6c85-4405-9001-431d8f54bd06)


@markus-moser when should the version column be purple and select styled and when not?

I added the style for every entry ... see:
![image](https://github.com/pimcore/studio-ui-bundle/assets/16717695/5aa393e6-1728-4140-b3e5-d46027f4d187)

**Comment by markus-moser** [comment]
@Corepex That's a good point. Let's style it always with the purple select styling like in your suggestion.
