### ISSUE TITLE
[Schedule] Version picker

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-ui-bundle#368]
Version picker with just IDs will not work (it's too hard to find out the right version).

![image](https://github.com/pimcore/studio-ui-bundle/assets/4639428/0c6aba57-4b16-4412-b02d-28fc19bfb3eb)

We also need to show the version date/time (with seconds) and version author like in the classic bundle:

![image](https://github.com/pimcore/studio-ui-bundle/assets/4639428/42a54c4f-2ac9-416d-aad8-21503e006746)

Would it be possible to show all 3?
- version ID
- date + time (with seconds)
- author

Related to #348

**Comment by Corepex** [comment]
Screendesign: https://www.figma.com/design/kTxowT29eCHwNh5NspDGGu/Pimcore-Components?node-id=4182-208989&m=dev
