### ISSUE TITLE
[Notes&Events] User is not displayed

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-ui-bundle#393]
In the classic UI bundle the user is visible in the `user` column.

![image](https://github.com/pimcore/studio-ui-bundle/assets/4639428/b08b5095-1898-4cc8-bc0e-7cd337570bb0)

In the new UI it's not visible. As far as I can see it's also not part of the design. 

@idaiv Could you please check the design and then hand over the issue to @robertSt7, thanks!

Related to #389

**Comment by idaiv** [comment]
Hi @markus-moser & @robertSt7! 
The user is now included: https://www.figma.com/design/kTxowT29eCHwNh5NspDGGu/Pimcore-Components?node-id=3037-146541&t=lmmFJQexSPQIO0LT-4

**Comment by idaiv** [comment]
Hi @robertSt7! The additional changes are approved :)

**Comment by markus-moser** [comment]
@robertSt7 This seems to somehow still does not work 100%:

* For items with description the user is not displayed 
* For items without description it is displayed but without some space next to the title

![Image](https://github.com/user-attachments/assets/49b760d8-a1b3-4a6d-9f95-75d150c1e947)

**Comment by robertSt7** [comment]
@markus-moser I fixed the space, but I think the user isn't in the response of the backend. Could you please check that? Thx

**Comment by markus-moser** [comment]
@robertSt7 You are right, the problem is that the user gets not saved in the backend API when a note is added. I'll create an issue for that (see [#272](https://github.com/pimcore/studio-backend-bundle/issues/272)).

Regarding the space topic - it works now, but it looks really strange when there is one entry with description and one without:

![image](https://github.com/user-attachments/assets/37d60809-a5c2-4054-94eb-b65e1af61ae4)

@idaiv Could you please add an example for that case to the design?

**Comment by idaiv** [comment]
Hi @markus-moser and @robertSt7! Sorry for the delay on the task. The design is reviewed and approved :)

Link: https://www.figma.com/design/kTxowT29eCHwNh5NspDGGu/Pimcore-Components?node-id=3037-146541&t=XuuBIvPJ6ynSxhl2-4
