### ISSUE TITLE
[Notes&Events] Notes without details and description

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-ui-bundle#394]
Without details and description an empty panel will be shown:

![image](https://github.com/pimcore/studio-ui-bundle/assets/4639428/1c94bd91-6bfc-44e2-9b20-0715f9d62c9d)

@idaiv What's your opinion on that? Should we hide the arrow for the details panel in that case or should we still show it and add some kind of empty message in the detail panel? Or do you have any other suggestion?

Related to #389

**Comment by idaiv** [comment]
Hi @robertSt7! The additional changes are approved and here you can find them: https://www.figma.com/design/kTxowT29eCHwNh5NspDGGu/Pimcore-Components?node-id=3037-146541&t=lmmFJQexSPQIO0LT-4

**Comment by markus-moser** [comment]
Fixed via #389
