### ISSUE TITLE
[Dependencies] Path column for long values

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-ui-bundle#408]
Is there a chance that we change the table to 100% width (with fixed column sizes for subtype + open and a flexible with for the path column)?

Currently the path will not be visible relatively fast:

![image](https://github.com/user-attachments/assets/227c5e3a-1bb3-4ec1-ab3d-9a57df694ff8)

Whereas in the classic bundle also very long paths can be shown without a problem:

![image](https://github.com/user-attachments/assets/19f75835-4caa-4bd7-aef8-ccc622ca033b)

Related to #388

**Comment by Corepex** [comment]
Should be definitely possible but thats the topic we put on-hold if i remember it correctly because it conflicts with the resizing of the table ...

**Comment by markus-moser** [comment]
Fixed now
