### ISSUE TITLE
Remove interconnected widget

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-ui-bundle#436]
I'd say it's time to remove the demo widget:

![image](https://github.com/user-attachments/assets/70796fc5-813f-4ec3-aeb6-cfd12979f2d6)

@vin0401 Do you agree?

**Comment by vin0401** [comment]
Yep, we can definitely remove it. :)

We just wanted to keep it until we have content for the bottom area. 
I guess, with tabs we have more than enough. ;D
