### ISSUE TITLE
[Versions] Expose /element/delete-all-versions in Studio

### ISSUE THREAD

**Issue by xIrusux** [pimcore/studio-ui-bundle#466]
Can we expose this same endpoint in the studio to allow clearing all versions (including published)
![image](https://github.com/user-attachments/assets/05d6e33c-b6ca-4a76-b1de-d51a9d33e5e5)

Related to #358

**Comment by lukmzig** [comment]
@xIrusux this endpoint is having the same functionality as delete-all-versions
https://github.com/pimcore/studio-backend-bundle/blob/1.x/src/Version/Controller/Element/CleanupController.php#L56

**Comment by xIrusux** [comment]
Discussed with @markus-moser and @lukmzig. 
Classic UI clears all versions (including the published one) from the UI without actually deleting them.

The studio api is consistent with the classic api endpoint and we are adjusting the UI. Thanks all!
