### ISSUE TITLE
Custom asset metadata types extendable?

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-ui-bundle#476]
In the old UI it is possible to register custom asset metadata types via ExtJS so that they appear in the select list:

![image](https://github.com/user-attachments/assets/e2543da6-4e27-46e5-b98f-a394b6497eb6)

In the new UI the type list is hardcoded. Do we need to provide the possibility to add custom types there (in addition to the asset metadata class definitions...)?

**Comment by markus-moser** [comment]
@fashxp WDYT?

**Comment by fashxp** [comment]
Yes we will need that ... Also for the asset metadata class definitions extension

**Comment by markus-moser** [comment]
Yes I know that the asset metadata class definitions extension uses the same types, but It' still a bit of a different case. For the asset metadata class definitions extension we do not need this as it does not hook into this select box - it stays the same also wenn the class definitions bundle is intalled. The question is if we need custom custom metadata types. For the data column we have already an extendable approach...

**Comment by fashxp** [comment]
I see. For now I think it is fine. 
Maybe at some point in the future we will need to add the extensibility though.
