### ISSUE TITLE
revisit checkbox cell 

### ISSUE THREAD

**Issue by xIrusux** [pimcore/studio-ui-bundle#494]
related to #489

ensure checkbox in properties and custom metadata table persists data and shows as "modified" after edit. 

there are several different cell-types around that include checkboxes which need a refactor to become one (i.e  checkbox-cell.tsx / boolean-cell.tsx / the way the checkbox is ingested in properties/components/table.table.tsx )

**Comment by markus-moser** [comment]
is fixed now
