### ISSUE TITLE
Select component / styling

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-ui-bundle#510]
Currently e.g. in the properties tab we have a special styling for select boxes:

https://github.com/pimcore/studio-ui-bundle/blob/1caa5f47dd4b8f09d3f1767588ec94bc44749fe0/assets/js/src/core/modules/asset/editor/shared-tab-manager/tabs/properties/properties-container.styles.tsx#L72

This transforms it from this

![image](https://github.com/user-attachments/assets/5aabcb90-0f19-46f8-9fbf-cc531878fcd6)

to this

![image](https://github.com/user-attachments/assets/49a269b4-7667-49bb-a508-67f139416b09)

We should provide a centralized select component which provides the styling options we need and re-use it everywhere.

Also in the data grid design we need to think about how select boxes should look like. The design of the scheduler e.g. looks like this:

![image](https://github.com/user-attachments/assets/803b724c-1943-440c-a878-552b7b0f6ab3)

I unified it to the default ant design select design. We should re-style it in the `SelectCell` centrally so that it looks the same everywhere.

**Comment by ValeriaMaltseva** [comment]
**The design part:**
https://github.com/pimcore/product-management/issues/642#issue-2564741769
https://www.figma.com/design/lomefPHRhJnkljB2nXtuKV/Ant-Design-5.11?node-id=1226-85112&node-type=frame&m=dev
