### ISSUE TITLE
Improve UX of split layout resizer

### ISSUE THREAD

**Issue by vin0401** [pimcore/studio-ui-bundle#544]
The current version of our split-layout needs a bit of an improvement in terms of UX.

The resizer is hard to use and provides to less user information in regards to the interactivity.
The improved behavior is noted down here:

https://www.figma.com/design/kTxowT29eCHwNh5NspDGGu/Pimcore-Components?node-id=6082-240242&node-type=canvas&t=3CCqdBd2pVVmoxO2-0

**Comment by ValeriaMaltseva** [comment]
Agreed that the user should always see the resizer button, even if this functionality isn’t available (when the section width is less than the minimum width).
