### ISSUE TITLE
Wrapping Tag Shared Component

### ISSUE THREAD

**Issue by xIrusux** [pimcore/studio-ui-bundle#550]
https://www.figma.com/design/kTxowT29eCHwNh5NspDGGu/Pimcore-Components?node-id=5594-229685&m=dev

![Image](https://github.com/user-attachments/assets/ca2fba1a-d0e4-4953-98cb-4d55f75a367f)

**Comment by vin0401** [comment]
I think we could create an own component for the divider used under the tags. 
Maybe it also makes sense to handle that in a own issue.

**Comment by idaiv** [comment]
Hi all @ValeriaMaltseva and @vin0401! As we discussed in our call, certain adjustments were needed and some more written information on the functionality. There is a dedicated Figma page now for this Tag Group Accordion here: https://www.figma.com/design/kTxowT29eCHwNh5NspDGGu/Pimcore-Components?node-id=6380-233277

Please take a look at the notes and feel free to reach out!
