### ISSUE TITLE
[Bug] mark active window

### ISSUE THREAD

**Issue by heigpa** [pimcore/studio-ui-bundle#597]
**Steps to reproduce**

- Login as admin
- Open 2 asstes side by side
- Detach the Embedded Metainfo

**Actual behaviour**
You do not see which window is the active one.
![Image](https://github.com/user-attachments/assets/2120109b-a4ce-485b-8d3a-aed50f24f55c)

**Expected behaviour**
You should see a breadcrumb in the detached window to identify which window is the active one.

**Environment**

- Nightly build

**Comment by markus-moser** [comment]
The breadcrumb is now available.
