### ISSUE TITLE
[Bug] Tab navigation cropped if breadcrump is too long

### ISSUE THREAD

**Issue by heigpa** [pimcore/studio-ui-bundle#599]
**Steps to reproduce**

- Login as admin
- Open two assets side by side

**Actual behaviour**

- Top navigation is cropped if breadcrumb is too long.

![Image](https://github.com/user-attachments/assets/dcd5e70c-bee3-41aa-9932-57bd2099333e)
![Image](https://github.com/user-attachments/assets/238b7e1c-9d99-4bc5-9c07-2abef389c560)

**Expected behaviour**

- Top navigation should be shown without cropping.

**Environment**

- Nightly build

**Comment by markus-moser** [comment]
@ValeriaMaltseva I think this is fixed now - could you please quickly check if it fine now and then close the issue, so that @heigpa can re-test it?

**Comment by ValeriaMaltseva** [comment]
The issue was fixed.

![Image](https://github.com/user-attachments/assets/c5838e3f-a74c-4607-ab0e-d3db079bb51b)

**Comment by heigpa** [comment]
Works now.
