### ISSUE TITLE
[Bug] download does not work

### ISSUE THREAD

**Issue by heigpa** [pimcore/studio-ui-bundle#601]
**Steps to reproduce**

- Login as admin
- Open an asset
- Try to download any format

**Actual behaviour**

- Nothing happens

![Image](https://github.com/user-attachments/assets/fe38eb66-f3d8-4a2c-8b44-9b7c60af1ddb)

**Expected behaviour**

- File in the correct format should be downloaded

**Environment**

- Nightly build

**Comment by Corepex** [comment]
This is an Issue just on the nightly.

![Image](https://github.com/user-attachments/assets/fb7aa07a-8c6c-4316-95f5-a797b1862b60)


I don't have any problems with my local machine.

**Comment by Corepex** [comment]
@markus-moser created a followup to address the issue with the fixed prefix. https://github.com/pimcore/studio-ui-bundle/issues/729
