### ISSUE TITLE
[Bug] 3 dot menu in folder preview does not work correct

### ISSUE THREAD

**Issue by heigpa** [pimcore/studio-ui-bundle#607]
**Steps to reproduce**

- Login as admin
- Open a folder with assets
- Open the 3 dot menu on one of the asset
- Click on any of the entries

**Actual behaviour**
- Preview of the asset is opened regardless of the entry that is choosen (delete, download as zip...)

![Image](https://github.com/user-attachments/assets/3155cea3-937a-49c5-8d1c-f6ad6bfa684f)

**Expected behaviour**

- Associated action is performed

**Environment**

- Nightly build

**Comment by markus-moser** [comment]
We are still working on this topic

**Comment by Corepex** [comment]
Seems to be fixed - cant reproduce it in the current build

**Comment by heigpa** [comment]
Retested it and for me it works now.
