### ISSUE TITLE
[Bug] number of results per page disappears when opening the tag filter

### ISSUE THREAD

**Issue by heigpa** [pimcore/studio-ui-bundle#610]
**Steps to reproduce**

- Login as admin
- Open the root folder of the car images
- Open the tag filter

**Actual behaviour**

- Selector for changing the results per page is not shown anymore

![Image](https://github.com/user-attachments/assets/c430580e-9515-4b7e-9556-a9e33d60249a)

**Expected behaviour**

- Selector should be shown

**Environment**

- Nightly build

**Screen resolution** 
- 1920 x 1080

**Comment by markus-moser** [comment]
@xIrusux We have now our horizontal scroll in place there, right? Could you please check if this issue is still relevant and otherwise close it so that @heigpa can retest it?

**Comment by xIrusux** [comment]
![Image](https://github.com/user-attachments/assets/865fc491-826d-4be6-8772-5e0f8c8df54d)
I am closing this issue as it has been fixed by the horizontal scroll bar, see above.

**Comment by heigpa** [comment]
Works now,
