### ISSUE TITLE
[Bug] tag filter in list view do not work

### ISSUE THREAD

**Issue by heigpa** [pimcore/studio-ui-bundle#611]
**Steps to reproduce**

- Login as admin
- Open a folder with assets
- Open the tag filter

**Actual behaviour**

- Nothing can be done in the filter section

![Image](https://github.com/user-attachments/assets/99208f5f-2193-4b13-aedd-e51c00eea328)

**Expected behaviour**

- Filters should be shown

**Environment**

- Nightly build

**Comment by ValeriaMaltseva** [comment]
This functionality is working now.

**Comment by heigpa** [comment]
Retested. Works now.
