### ISSUE TITLE
[Bug] linked assets are opened in the object editor

### ISSUE THREAD

**Issue by heigpa** [pimcore/studio-ui-bundle#617]
**Steps to reproduce**

- Login as admin in the Classic UI
- Open an asset
- Open the properties tab
- Add a new property to link an asset
- Link an asset
- Change to the studio-ui
- Open the asset
- Open the properties tab
- Click on the link to the asset

**Actual behaviour**

- The asset gets opened in the object editor

![Image](https://github.com/user-attachments/assets/58a0a836-6a35-4bc9-86f2-66e3f196519d)

**Expected behaviour**

- Asset should be opened in the asset editor

**Environment**

- Nightly build

**Comment by Corepex** [comment]
seems to be fixed 🥇 (double checked with @heigpa )

**Comment by heigpa** [comment]
Works now.
