### ISSUE TITLE
[Improvement] save and publish in folder view and list view

### ISSUE THREAD

**Issue by heigpa** [pimcore/studio-ui-bundle#625]
Does a save and publish button in the preview for folders and list view make sense?

![Image](https://github.com/user-attachments/assets/b1789885-7b78-484a-a03d-8b121fa0fda2)

**Comment by markus-moser** [comment]
@heigpa It's needed to save the properties. In theory it could go to the properties tab but then the behaviour would be different based on the type. Also maybe someone created plugins to save additional information to folders. I would say: let's leave it just there!
