### ISSUE TITLE
[Bug] batch edit wrong options

### ISSUE THREAD

**Issue by heigpa** [pimcore/studio-ui-bundle#642]
**Steps to reproduce**

- Login as admin
- open a car folder
- change to the list view
- mark multiple car images
- start a batch editing process

**Actual behaviour**

- The options for the batch editing do not match the predefined metadata fields

![Image](https://github.com/user-attachments/assets/d1175425-de30-4e4a-9dab-1fbe40e7f252)
![Image](https://github.com/user-attachments/assets/8c2ca451-6045-44b5-b1c1-f7039716de77)

**Expected behaviour**

- Options should match the predefined metadata fields
- Modification date should not be included

**Environment**

- Nightly build

**Comment by markus-moser** [comment]
This is not a bug -> we need to implement the asset metadata class definitions bundle. At the moment we only have the options which are available in the non-enterprise version.
