### ISSUE TITLE
[Bug] version did not get deleted via scheduler

### ISSUE THREAD

**Issue by heigpa** [pimcore/studio-ui-bundle#647]
**Steps to reproduce**

- Login as admin
- Open an image editor
- Open scheduler tab
- Add an entry to delete an old version

**Actual behaviour**
![Image](https://github.com/user-attachments/assets/ec4de0be-9232-48bd-a026-be98f00d0c2b)
![Image](https://github.com/user-attachments/assets/abe8a45b-c382-4c3e-95d2-244e27901c3e)

- Old version did not get deleted

**Expected behaviour**

- Old version should be deleted

**Environment**

- Nightly build

**Comment by markus-moser** [comment]
Please check if the entered information are the same in studio UI and the classic bundle. We should concentrate on the UI part - if the values are saved and displayed the same way like in the classic bundle the UI works. If it does not get deleted it's more like a general Pimcore topic - maybe some problem in your instance.
