### ISSUE TITLE
[Bug] zip download in list view does not work

### ISSUE THREAD

**Issue by heigpa** [pimcore/studio-ui-bundle#649]
**Steps to reproduce**

- Login as admin
- Open a folder
- Switch to the list view
- Mark some assets
- Download images as a zip file

**Actual behaviour**

- Zip download does not work

![Image](https://github.com/user-attachments/assets/13764358-3dfc-4899-b804-d6751ddeec9b)

**Expected behaviour**

- Images should be downloaded as a zip file

**Environment**

- Nightly build

**Comment by fashxp** [comment]
works for me

**Comment by markus-moser** [comment]
@heigpa Please re-test it, thanks

**Comment by heigpa** [comment]
@markus-moser works now
