### ISSUE TITLE
[Bug] rendering error in detached version window

### ISSUE THREAD

**Issue by heigpa** [pimcore/studio-ui-bundle#651]
**Steps to reproduce**

- Login as admin
- Open multiple assets
- Detach the version tab
- Switch from one active asset editor window to the other

**Actual behaviour**

- Rendering error appears

![Image](https://github.com/user-attachments/assets/bb216e71-386f-4c52-903e-e4480fdfa8ae)

**Expected behaviour**

- Versions should be shown in the detached windoe

**Environment**

- Nightly build

**Comment by markus-moser** [comment]
related to #646
