### ISSUE TITLE
Add tooltips to widget toolbar

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-ui-bundle#679]
We would need tooltips for those buttons on the left and right side to switch between the (tree) widgets:

![Image](https://github.com/user-attachments/assets/3aa611ae-5000-4f60-b41d-5ead6e12992a)

**Comment by dpfahlbusch** [comment]
Heyho :)
Maybe a minor idea for improving the tooltips:
In my opinion the tooltip should appear when you hover over the button and not when you hover over the icon of the button :)
WDYT?
