### ISSUE TITLE
Element Icons

### ISSUE THREAD

**Issue by fashxp** [pimcore/studio-ui-bundle#68]
- icons per element type
- custom icons for custom element types (e.g. custom asset types, data object classes) 
   - project specific icons should be possible

**Comment by markus-moser** [comment]
**@pimcore-studio-backend-team**

Please provide a tree endpoint based on the generic data index with a specialized/reduced result object just for the tree and implement the icon logic there.

For the tree we have some special customization requirements for our customers to customize the tree view - this should be done via provided events:
* icon
* tooltip
* additional icons like in this screen
![image](https://github.com/pimcore/studio-ui-bundle/assets/4639428/679e1bd5-0dde-4961-b6b1-85930492458c)
(see #69)
* filename/key
* additional CSS class(es) for the tree node

This is somehow a similar topic like this approach in the classic UI bundle: https://pimcore.com/docs/platform/Pimcore/Tools_and_Features/Custom_Icons

In addition to that there is also an event to manipulate the full json. Don't think that we should do this but just provide some options for the mentioned things.

You will find some more information here: https://pimcore.atlassian.net/wiki/spaces/PD/pages/4082991116/Concept+Interaction+Studio+Backend+UI+and+Generic+Data+Index

Maybe it could be a good idea to arrange a meeting together with @vin0401 and me to discuss some details.

**Comment by lukmzig** [comment]
Tree endpoint was adapter and is available under https://github.com/pimcore/studio-backend-bundle/blob/1.x/src/Asset/Controller/TreeController.php#L66
