### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by fashxp** [pimcore/studio-ui-bundle#71]
- system features like
   - add folder
   - add asset
   - rename
   - delete
   - copy, cut, paste
   - upload new version
   - locking
- manageable via permissions
   - show/hide certain entries
   - information needs to be delivered from API
- need to have alternative access for all features in element's toolbar more menu

![image](https://github.com/pimcore/studio-ui-bundle/assets/8792145/87b46177-a3b0-4aac-88fd-5ca1faf05c72)

https://www.figma.com/design/kTxowT29eCHwNh5NspDGGu/Pimcore-Components?node-id=3021-124279&t=TH6LzmPptxSxTMON-4

- should be extendable via bundles

**Comment by markus-moser** [comment]
**@pimcore-studio-backend-team**

Please check which endpoints are missing to allow the mentioned operations.

e.g.
* Asset deletion
* Create folder

The upload features should be done then in a separate issue, so please consider it as out of scope for this one.

**Comment by lukmzig** [comment]
@markus-moser could you please elaborate about concept a bit more for these 2 points?

- manageable via permissions
  - show/hide certain entries
  - information needs to be delivered from API

what information would you need here? should it not be a part of tree endpoint?

- need to have alternative access for all features in element's toolbar more menu
Is there something API needs to deliver?

**Comment by markus-moser** [comment]
@lukmzig Everything what we need regarding permissions is the permission set from the generic data index bundle which you implemented there. This needs to be part of the tree endpoint.

For the entries in the more menu we do not need something special:

* for the copy/paste features you created already endpoints in the linked PRs
* the lock features can be done via the regular asset update endpoint (Matthias implemented it already there)
* Upload will be a separate issue
* For the download we have already an endpoint, right?
* And the "request translation" entry comes from an additional bundle (translation provider interfaces)

**Comment by lukmzig** [comment]
Just a short summary:

- add folder - endpoint is available here: https://github.com/pimcore/studio-backend-bundle/blob/1.x/src/Element/Controller/FolderController.php#L65
- add asset (Will be handled by separate ticket) 
- rename - can be done via asset update endpoint
- delete - endpoint was added here: https://github.com/pimcore/studio-backend-bundle/pull/327/files#diff-8409c9629f3173ad9082522e3fbcbd3d8bdda33a891c11a5a1d596efeb1def8fR67 (single element is deleted synchornously, elements with children are deleted by GEE and SSE)
- copy, paste - endpoint was added here: https://github.com/pimcore/studio-backend-bundle/blob/1.x/src/Asset/Controller/CloneController.php#L63 (single element is cloned synchornously, elements with children are cloned by GEE and SSE)
- cut - can be done via asset patch endpoint (changing the parentId)
- upload new version - (Will be handled by separate ticket) 
- locking - can be done via asset patch endpoint

permissions will be delivered via tree endpoint
