### ISSUE TITLE
[Detached Tabs Widget] Add breadcrumbs

### ISSUE THREAD

**Issue by markus-moser** [pimcore/studio-ui-bundle#721]
We need our tab-bar also in the detached tab widgets as otherwise its impossible to see to which asset the tab belongs when multiple elements are openend in parallel:

![Image](https://github.com/user-attachments/assets/2be5a4d0-d786-4b32-922d-fe691b70ded4)

![Image](https://github.com/user-attachments/assets/4346cc3f-d624-4068-b176-445ceb7f20ff)

**Comment by markus-moser** [comment]
@idaiv Do we have an example in the design for the breadcrumb of the detached tabs widget? Could you please add a link? Thx!

**Comment by idaiv** [comment]
Hi @markus-moser! Yes, we have designed it already: https://www.figma.com/design/kTxowT29eCHwNh5NspDGGu/Pimcore-Components?node-id=2972-103910&t=BsgQgRrMRo4jxfTo-4 and thats the component on its own: https://www.figma.com/design/kTxowT29eCHwNh5NspDGGu/Pimcore-Components?node-id=3-1275&t=BsgQgRrMRo4jxfTo-4

**Comment by markus-moser** [comment]
@idaiv Cool, thanks a lot
