### ISSUE TITLE
Asset Preview

### ISSUE THREAD

**Issue by fashxp** [pimcore/studio-ui-bundle#75]
For different asset types
- image
- video
- documents ( = pdf preview)
- text files → see also Asset Text Editor

![image](https://github.com/pimcore/studio-ui-bundle/assets/8792145/614c502d-d08f-4869-911a-91eb5c51dbd2)

![image](https://github.com/pimcore/studio-ui-bundle/assets/8792145/1c02cbd2-929c-4c11-ad8f-3ecb7fb6fb66)

![image](https://github.com/pimcore/studio-ui-bundle/assets/8792145/daa77a1a-0c6e-4d20-96c8-1758314c5e70)

**Comment by vin0401** [comment]
Audio type is missing.

**Comment by mattamon** [comment]
> Audio type is missing.

API or UI wise?
At least the type is implemented in the API, but never really worked with it.

**Comment by vin0401** [comment]
ahh, sorry UI wise. :D 
I think from API side it should be fine. :)

**Comment by robertSt7** [comment]
@mattamon the `/asset/get-preview-document` endpoint is missing. Could you please take a look at this? Thanks

**Comment by markus-moser** [comment]
@mattamon Please let me know when we should add a separate issue for this topic, thanks!

**Comment by mattamon** [comment]
> [@mattamon](https://github.com/mattamon) Please let me know when we should add a separate issue for this topic, thanks!

@markus-moser I had a look and this is way more complicated that anticipated. There is a lot going on. I would suggest opening a separate ticket for this.

**Comment by markus-moser** [comment]
@mattamon I created this issues and added it to the backend studio development board so that you can decide together who should work on it: https://github.com/pimcore/studio-backend-bundle/issues/114 

Please let me know if you need anything else 👍

**Comment by markus-moser** [comment]
@robertSt7 
- e.g. zip files do not have a preview -> hide tab in that case
- document preview endpoint (as PDF) is now available
- please ask the backend team if there are any other known special cases
