### ISSUE TITLE
Grid reload is missing

### ISSUE THREAD

**Issue by fashxp** [pimcore/studio-ui-bundle#778]
![Image](https://github.com/user-attachments/assets/aa7c6bac-ae7b-4973-a143-84234a5eba8b)

button to reload the grid with current configuration

**Comment by vin0401** [comment]
@idaiv - Haven't seen a screen with this refresh included.

Should we do it like in the classic UI? Having just the simple refresh icon with a divider next to the total.
Or would you prefer something different?

**Comment by idaiv** [comment]
Hi @marvin, I have updated it now in the design system directly: https://www.figma.com/design/Q2AzPxCsXKxpbPWrB64ekW/Ant-Design-5.21-(Test-File)?node-id=415-205&t=kaxkuukZakSqF6HM-4
(follows the final refresh icon, our divider and in the Ant 5.21 file)
