### ISSUE TITLE
PQL tooltip

### ISSUE THREAD

**Issue by fashxp** [pimcore/studio-ui-bundle#780]
add a nice next, not just the link :-) 

![Image](https://github.com/user-attachments/assets/2544e9c0-2943-465d-aab4-3fbd83259e4d)

**Comment by idaiv** [comment]
Can we instead embed the link and use the description from the page: "The PqlFilter search modifier can be used with the search services provided by the Generic Data Index bundle. Take a look at the [Search Services](https://docs.pimcore.com/platform/next/Generic_Data_Index/Searching_For_Data_In_Index/) documentation for details." 
WDYT @fashxp

**Comment by fashxp** [comment]
Nope, that text and the link are wrong 😄. It should more say something like: 

Pimcore Query Language (PQL) is a simple yet powerful query language that lets you search data using various criteria, including filtering values in related elements, to enable precise and comprehensive data retrieval. For details see [PQL Documentation](https://docs.pimcore.com/platform/next/Generic_Data_Index/Searching_For_Data_In_Index/Pimcore_Query_Language/)
