### ISSUE TITLE
DataObject Editor - different font styling

### ISSUE THREAD

**Issue by fashxp** [pimcore/studio-ui-bundle#795]
fonts of text areas look completely different to input fields

![Image](https://github.com/user-attachments/assets/61b48e47-fe3c-4c2e-a20c-3a78337ea8b4)

**Comment by markus-moser** [comment]
Interesting, on my local it looks exactly the same - maybe it's related to #763

**Comment by markus-moser** [comment]
@vin0401 will check the missing font

**Comment by fashxp** [comment]
Chrome in linux ... Maybe a browser issue

**Comment by vin0401** [comment]
Fixed via: https://github.com/pimcore/studio-ui-bundle/pull/810
