### ISSUE TITLE
Asset Video Sidebar

### ISSUE THREAD

**Issue by fashxp** [pimcore/studio-ui-bundle#80]
- Show video dimensions
- change video thumbnail for preview
- download video
- image preview → see Aset Video Image Preview

![image](https://github.com/pimcore/studio-ui-bundle/assets/8792145/50cf0461-3422-46cd-8d6b-9b9fd6220777)

**Comment by lukmzig** [comment]
There are several endpoints relevant for the sidebar:

- list of video thumbnails can be obtained by calling this endpoint: https://github.com/pimcore/studio-backend-bundle/blob/1.x/src/Thumbnail/Controller/VideoCollectionController.php#L52

- it is possible to the video preview by calling this endpoint
    - https://github.com/pimcore/studio-backend-bundle/pull/107/files#diff-f319a46d037d9294eceb1ac7125436c7a0b0b535d4d49ea30765bbe82d5f5f46R69
    - you need to pass the video ID and thumbnail id from the previous call

- to download the original video you can use this endpoint: https://github.com/pimcore/studio-backend-bundle/pull/93/files#diff-cf83d5db9ad3a983aaacc586e6fcac9c2c32d0406a48991f25711c1f65994307R61

- it is also possible to download video by thumbnail configuration name by calling this endpoint: https://github.com/pimcore/studio-backend-bundle/pull/107/files#diff-ad23d90c5f3b2d80f1236aa0338e0b78715d01c5c7e61f0c9aa9d81819862577R69
