### ISSUE TITLE
Asset Video Image Preview

### ISSUE THREAD

**Issue by fashxp** [pimcore/studio-ui-bundle#81]
- Define image preview for video
- either via assigning an asset image
- or via selecting current player position

![image](https://github.com/pimcore/studio-ui-bundle/assets/8792145/ffcdc058-4555-4fbe-90d8-7b284e58a0aa)

![image](https://github.com/pimcore/studio-ui-bundle/assets/8792145/90dd3602-1968-45ad-810f-2ca9114f2eea)

**Comment by lukmzig** [comment]
To update the video image thumbnail please use the update endpoint. This is done same way as in the core - by updating the custom settings (https://github.com/pimcore/admin-ui-classic-bundle/blob/1.x/src/Controller/Admin/Asset/AssetController.php#L1300-L1315): 
- for using the time send custom settings with the key "image_thumbnail_time" and the time value
- for using asset please pass the key "image_thumbnail_asset" and the asset ID

to get the video image thumbnail back use this endpoint:
https://github.com/pimcore/studio-backend-bundle/pull/107/files#diff-7232bfd5989ad7406a30d01e51a28f284a36c2ce97d7ece95640a6668f9af661R74
there you can pass configuration which you need, similar to the current UI
e.g
https://github.com/pimcore/admin-ui-classic-bundle/blob/1.x/public/js/pimcore/asset/video.js#L217-L219
